//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP2Soft.MedicinaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.lp2myclinic/", ConfigurationName="MedicinaWS.MedicinaWS")]
    public interface MedicinaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/listarMedicinasTodasParaAlmacenistaRequest" +
            "", ReplyAction="http://services.lp2myclinic/MedicinaWS/listarMedicinasTodasParaAlmacenistaRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaResponse listarMedicinasTodasParaAlmacenista(LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/listarMedicinasTodasParaAlmacenistaRequest" +
            "", ReplyAction="http://services.lp2myclinic/MedicinaWS/listarMedicinasTodasParaAlmacenistaRespons" +
            "e")]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaResponse> listarMedicinasTodasParaAlmacenistaAsync(LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/buscarMedicamentosRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/buscarMedicamentosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.MedicinaWS.buscarMedicamentosResponse buscarMedicamentos(LP2Soft.MedicinaWS.buscarMedicamentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/buscarMedicamentosRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/buscarMedicamentosResponse")]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.buscarMedicamentosResponse> buscarMedicamentosAsync(LP2Soft.MedicinaWS.buscarMedicamentosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/listarInventarioRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/listarInventarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.MedicinaWS.listarInventarioResponse listarInventario(LP2Soft.MedicinaWS.listarInventarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/listarInventarioRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/listarInventarioResponse")]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarInventarioResponse> listarInventarioAsync(LP2Soft.MedicinaWS.listarInventarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/obtenerMedicamentoRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/obtenerMedicamentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.MedicinaWS.obtenerMedicamentoResponse obtenerMedicamento(LP2Soft.MedicinaWS.obtenerMedicamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/obtenerMedicamentoRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/obtenerMedicamentoResponse")]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.obtenerMedicamentoResponse> obtenerMedicamentoAsync(LP2Soft.MedicinaWS.obtenerMedicamentoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/listar_inventario_x_fechasRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/listar_inventario_x_fechasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.MedicinaWS.listar_inventario_x_fechasResponse listar_inventario_x_fechas(LP2Soft.MedicinaWS.listar_inventario_x_fechasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/listar_inventario_x_fechasRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/listar_inventario_x_fechasResponse")]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listar_inventario_x_fechasResponse> listar_inventario_x_fechasAsync(LP2Soft.MedicinaWS.listar_inventario_x_fechasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/insertarMedicamentoRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/insertarMedicamentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.MedicinaWS.insertarMedicamentoResponse insertarMedicamento(LP2Soft.MedicinaWS.insertarMedicamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/insertarMedicamentoRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/insertarMedicamentoResponse")]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.insertarMedicamentoResponse> insertarMedicamentoAsync(LP2Soft.MedicinaWS.insertarMedicamentoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/eliminarInventarioRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/eliminarInventarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.MedicinaWS.eliminarInventarioResponse eliminarInventario(LP2Soft.MedicinaWS.eliminarInventarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/eliminarInventarioRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/eliminarInventarioResponse")]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.eliminarInventarioResponse> eliminarInventarioAsync(LP2Soft.MedicinaWS.eliminarInventarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/listarInventarioMantenimientoRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/listarInventarioMantenimientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.MedicinaWS.listarInventarioMantenimientoResponse listarInventarioMantenimiento(LP2Soft.MedicinaWS.listarInventarioMantenimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/listarInventarioMantenimientoRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/listarInventarioMantenimientoResponse")]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarInventarioMantenimientoResponse> listarInventarioMantenimientoAsync(LP2Soft.MedicinaWS.listarInventarioMantenimientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/insertarInventarioRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/insertarInventarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.MedicinaWS.insertarInventarioResponse insertarInventario(LP2Soft.MedicinaWS.insertarInventarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/insertarInventarioRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/insertarInventarioResponse")]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.insertarInventarioResponse> insertarInventarioAsync(LP2Soft.MedicinaWS.insertarInventarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/listarMedicamentosTodosRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/listarMedicamentosTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.MedicinaWS.listarMedicamentosTodosResponse listarMedicamentosTodos(LP2Soft.MedicinaWS.listarMedicamentosTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2myclinic/MedicinaWS/listarMedicamentosTodosRequest", ReplyAction="http://services.lp2myclinic/MedicinaWS/listarMedicamentosTodosResponse")]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarMedicamentosTodosResponse> listarMedicamentosTodosAsync(LP2Soft.MedicinaWS.listarMedicamentosTodosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2myclinic/")]
    public partial class medicamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private componente componenteField;
        
        private string descripcionField;
        
        private int idMedicamentoField;
        
        private string nombreComercialField;
        
        private string nombreLaboratorioField;
        
        private float precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public componente componente {
            get {
                return this.componenteField;
            }
            set {
                this.componenteField = value;
                this.RaisePropertyChanged("componente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idMedicamento {
            get {
                return this.idMedicamentoField;
            }
            set {
                this.idMedicamentoField = value;
                this.RaisePropertyChanged("idMedicamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreComercial {
            get {
                return this.nombreComercialField;
            }
            set {
                this.nombreComercialField = value;
                this.RaisePropertyChanged("nombreComercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreLaboratorio {
            get {
                return this.nombreLaboratorioField;
            }
            set {
                this.nombreLaboratorioField = value;
                this.RaisePropertyChanged("nombreLaboratorio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public float precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2myclinic/")]
    public partial class componente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idComponenteField;
        
        private string nombreComponenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idComponente {
            get {
                return this.idComponenteField;
            }
            set {
                this.idComponenteField = value;
                this.RaisePropertyChanged("idComponente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreComponente {
            get {
                return this.nombreComponenteField;
            }
            set {
                this.nombreComponenteField = value;
                this.RaisePropertyChanged("nombreComponente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2myclinic/")]
    public partial class inventario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoLoteField;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private System.DateTime fechaIngresoField;
        
        private bool fechaIngresoFieldSpecified;
        
        private int idInventarioField;
        
        private medicamento medicamentoField;
        
        private int stockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoLote {
            get {
                return this.codigoLoteField;
            }
            set {
                this.codigoLoteField = value;
                this.RaisePropertyChanged("codigoLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
                this.RaisePropertyChanged("fechaCaducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
                this.RaisePropertyChanged("fechaCaducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
                this.RaisePropertyChanged("fechaIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaIngresoSpecified {
            get {
                return this.fechaIngresoFieldSpecified;
            }
            set {
                this.fechaIngresoFieldSpecified = value;
                this.RaisePropertyChanged("fechaIngresoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idInventario {
            get {
                return this.idInventarioField;
            }
            set {
                this.idInventarioField = value;
                this.RaisePropertyChanged("idInventario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public medicamento medicamento {
            get {
                return this.medicamentoField;
            }
            set {
                this.medicamentoField = value;
                this.RaisePropertyChanged("medicamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMedicinasTodasParaAlmacenista", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class listarMedicinasTodasParaAlmacenistaRequest {
        
        public listarMedicinasTodasParaAlmacenistaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMedicinasTodasParaAlmacenistaResponse", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class listarMedicinasTodasParaAlmacenistaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.MedicinaWS.medicamento[] @return;
        
        public listarMedicinasTodasParaAlmacenistaResponse() {
        }
        
        public listarMedicinasTodasParaAlmacenistaResponse(LP2Soft.MedicinaWS.medicamento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarMedicamentos", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class buscarMedicamentosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cadenaBusqueda;
        
        public buscarMedicamentosRequest() {
        }
        
        public buscarMedicamentosRequest(string cadenaBusqueda) {
            this.cadenaBusqueda = cadenaBusqueda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarMedicamentosResponse", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class buscarMedicamentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.MedicinaWS.medicamento[] @return;
        
        public buscarMedicamentosResponse() {
        }
        
        public buscarMedicamentosResponse(LP2Soft.MedicinaWS.medicamento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInventario", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class listarInventarioRequest {
        
        public listarInventarioRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInventarioResponse", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class listarInventarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.MedicinaWS.inventario[] @return;
        
        public listarInventarioResponse() {
        }
        
        public listarInventarioResponse(LP2Soft.MedicinaWS.inventario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMedicamento", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class obtenerMedicamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMedicamento;
        
        public obtenerMedicamentoRequest() {
        }
        
        public obtenerMedicamentoRequest(int idMedicamento) {
            this.idMedicamento = idMedicamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMedicamentoResponse", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class obtenerMedicamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public obtenerMedicamentoResponse() {
        }
        
        public obtenerMedicamentoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_inventario_x_fechas", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class listar_inventario_x_fechasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.MedicinaWS.inventario inventario;
        
        public listar_inventario_x_fechasRequest() {
        }
        
        public listar_inventario_x_fechasRequest(LP2Soft.MedicinaWS.inventario inventario) {
            this.inventario = inventario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar_inventario_x_fechasResponse", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class listar_inventario_x_fechasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.MedicinaWS.inventario[] @return;
        
        public listar_inventario_x_fechasResponse() {
        }
        
        public listar_inventario_x_fechasResponse(LP2Soft.MedicinaWS.inventario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMedicamento", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class insertarMedicamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.MedicinaWS.medicamento medicamento;
        
        public insertarMedicamentoRequest() {
        }
        
        public insertarMedicamentoRequest(LP2Soft.MedicinaWS.medicamento medicamento) {
            this.medicamento = medicamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMedicamentoResponse", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class insertarMedicamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarMedicamentoResponse() {
        }
        
        public insertarMedicamentoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarInventario", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class eliminarInventarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.MedicinaWS.inventario inventario;
        
        public eliminarInventarioRequest() {
        }
        
        public eliminarInventarioRequest(LP2Soft.MedicinaWS.inventario inventario) {
            this.inventario = inventario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarInventarioResponse", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class eliminarInventarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarInventarioResponse() {
        }
        
        public eliminarInventarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInventarioMantenimiento", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class listarInventarioMantenimientoRequest {
        
        public listarInventarioMantenimientoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInventarioMantenimientoResponse", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class listarInventarioMantenimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.MedicinaWS.inventario[] @return;
        
        public listarInventarioMantenimientoResponse() {
        }
        
        public listarInventarioMantenimientoResponse(LP2Soft.MedicinaWS.inventario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarInventario", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class insertarInventarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.MedicinaWS.inventario inventario;
        
        public insertarInventarioRequest() {
        }
        
        public insertarInventarioRequest(LP2Soft.MedicinaWS.inventario inventario) {
            this.inventario = inventario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarInventarioResponse", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class insertarInventarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarInventarioResponse() {
        }
        
        public insertarInventarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMedicamentosTodos", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class listarMedicamentosTodosRequest {
        
        public listarMedicamentosTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMedicamentosTodosResponse", WrapperNamespace="http://services.lp2myclinic/", IsWrapped=true)]
    public partial class listarMedicamentosTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2myclinic/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.MedicinaWS.medicamento[] @return;
        
        public listarMedicamentosTodosResponse() {
        }
        
        public listarMedicamentosTodosResponse(LP2Soft.MedicinaWS.medicamento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MedicinaWSChannel : LP2Soft.MedicinaWS.MedicinaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MedicinaWSClient : System.ServiceModel.ClientBase<LP2Soft.MedicinaWS.MedicinaWS>, LP2Soft.MedicinaWS.MedicinaWS {
        
        public MedicinaWSClient() {
        }
        
        public MedicinaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MedicinaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedicinaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedicinaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaResponse LP2Soft.MedicinaWS.MedicinaWS.listarMedicinasTodasParaAlmacenista(LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaRequest request) {
            return base.Channel.listarMedicinasTodasParaAlmacenista(request);
        }
        
        public LP2Soft.MedicinaWS.medicamento[] listarMedicinasTodasParaAlmacenista() {
            LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaRequest inValue = new LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaRequest();
            LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaResponse retVal = ((LP2Soft.MedicinaWS.MedicinaWS)(this)).listarMedicinasTodasParaAlmacenista(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaResponse> LP2Soft.MedicinaWS.MedicinaWS.listarMedicinasTodasParaAlmacenistaAsync(LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaRequest request) {
            return base.Channel.listarMedicinasTodasParaAlmacenistaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaResponse> listarMedicinasTodasParaAlmacenistaAsync() {
            LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaRequest inValue = new LP2Soft.MedicinaWS.listarMedicinasTodasParaAlmacenistaRequest();
            return ((LP2Soft.MedicinaWS.MedicinaWS)(this)).listarMedicinasTodasParaAlmacenistaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.MedicinaWS.buscarMedicamentosResponse LP2Soft.MedicinaWS.MedicinaWS.buscarMedicamentos(LP2Soft.MedicinaWS.buscarMedicamentosRequest request) {
            return base.Channel.buscarMedicamentos(request);
        }
        
        public LP2Soft.MedicinaWS.medicamento[] buscarMedicamentos(string cadenaBusqueda) {
            LP2Soft.MedicinaWS.buscarMedicamentosRequest inValue = new LP2Soft.MedicinaWS.buscarMedicamentosRequest();
            inValue.cadenaBusqueda = cadenaBusqueda;
            LP2Soft.MedicinaWS.buscarMedicamentosResponse retVal = ((LP2Soft.MedicinaWS.MedicinaWS)(this)).buscarMedicamentos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.buscarMedicamentosResponse> LP2Soft.MedicinaWS.MedicinaWS.buscarMedicamentosAsync(LP2Soft.MedicinaWS.buscarMedicamentosRequest request) {
            return base.Channel.buscarMedicamentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.MedicinaWS.buscarMedicamentosResponse> buscarMedicamentosAsync(string cadenaBusqueda) {
            LP2Soft.MedicinaWS.buscarMedicamentosRequest inValue = new LP2Soft.MedicinaWS.buscarMedicamentosRequest();
            inValue.cadenaBusqueda = cadenaBusqueda;
            return ((LP2Soft.MedicinaWS.MedicinaWS)(this)).buscarMedicamentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.MedicinaWS.listarInventarioResponse LP2Soft.MedicinaWS.MedicinaWS.listarInventario(LP2Soft.MedicinaWS.listarInventarioRequest request) {
            return base.Channel.listarInventario(request);
        }
        
        public LP2Soft.MedicinaWS.inventario[] listarInventario() {
            LP2Soft.MedicinaWS.listarInventarioRequest inValue = new LP2Soft.MedicinaWS.listarInventarioRequest();
            LP2Soft.MedicinaWS.listarInventarioResponse retVal = ((LP2Soft.MedicinaWS.MedicinaWS)(this)).listarInventario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarInventarioResponse> LP2Soft.MedicinaWS.MedicinaWS.listarInventarioAsync(LP2Soft.MedicinaWS.listarInventarioRequest request) {
            return base.Channel.listarInventarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarInventarioResponse> listarInventarioAsync() {
            LP2Soft.MedicinaWS.listarInventarioRequest inValue = new LP2Soft.MedicinaWS.listarInventarioRequest();
            return ((LP2Soft.MedicinaWS.MedicinaWS)(this)).listarInventarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.MedicinaWS.obtenerMedicamentoResponse LP2Soft.MedicinaWS.MedicinaWS.obtenerMedicamento(LP2Soft.MedicinaWS.obtenerMedicamentoRequest request) {
            return base.Channel.obtenerMedicamento(request);
        }
        
        public string obtenerMedicamento(int idMedicamento) {
            LP2Soft.MedicinaWS.obtenerMedicamentoRequest inValue = new LP2Soft.MedicinaWS.obtenerMedicamentoRequest();
            inValue.idMedicamento = idMedicamento;
            LP2Soft.MedicinaWS.obtenerMedicamentoResponse retVal = ((LP2Soft.MedicinaWS.MedicinaWS)(this)).obtenerMedicamento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.obtenerMedicamentoResponse> LP2Soft.MedicinaWS.MedicinaWS.obtenerMedicamentoAsync(LP2Soft.MedicinaWS.obtenerMedicamentoRequest request) {
            return base.Channel.obtenerMedicamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.MedicinaWS.obtenerMedicamentoResponse> obtenerMedicamentoAsync(int idMedicamento) {
            LP2Soft.MedicinaWS.obtenerMedicamentoRequest inValue = new LP2Soft.MedicinaWS.obtenerMedicamentoRequest();
            inValue.idMedicamento = idMedicamento;
            return ((LP2Soft.MedicinaWS.MedicinaWS)(this)).obtenerMedicamentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.MedicinaWS.listar_inventario_x_fechasResponse LP2Soft.MedicinaWS.MedicinaWS.listar_inventario_x_fechas(LP2Soft.MedicinaWS.listar_inventario_x_fechasRequest request) {
            return base.Channel.listar_inventario_x_fechas(request);
        }
        
        public LP2Soft.MedicinaWS.inventario[] listar_inventario_x_fechas(LP2Soft.MedicinaWS.inventario inventario) {
            LP2Soft.MedicinaWS.listar_inventario_x_fechasRequest inValue = new LP2Soft.MedicinaWS.listar_inventario_x_fechasRequest();
            inValue.inventario = inventario;
            LP2Soft.MedicinaWS.listar_inventario_x_fechasResponse retVal = ((LP2Soft.MedicinaWS.MedicinaWS)(this)).listar_inventario_x_fechas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listar_inventario_x_fechasResponse> LP2Soft.MedicinaWS.MedicinaWS.listar_inventario_x_fechasAsync(LP2Soft.MedicinaWS.listar_inventario_x_fechasRequest request) {
            return base.Channel.listar_inventario_x_fechasAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listar_inventario_x_fechasResponse> listar_inventario_x_fechasAsync(LP2Soft.MedicinaWS.inventario inventario) {
            LP2Soft.MedicinaWS.listar_inventario_x_fechasRequest inValue = new LP2Soft.MedicinaWS.listar_inventario_x_fechasRequest();
            inValue.inventario = inventario;
            return ((LP2Soft.MedicinaWS.MedicinaWS)(this)).listar_inventario_x_fechasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.MedicinaWS.insertarMedicamentoResponse LP2Soft.MedicinaWS.MedicinaWS.insertarMedicamento(LP2Soft.MedicinaWS.insertarMedicamentoRequest request) {
            return base.Channel.insertarMedicamento(request);
        }
        
        public int insertarMedicamento(LP2Soft.MedicinaWS.medicamento medicamento) {
            LP2Soft.MedicinaWS.insertarMedicamentoRequest inValue = new LP2Soft.MedicinaWS.insertarMedicamentoRequest();
            inValue.medicamento = medicamento;
            LP2Soft.MedicinaWS.insertarMedicamentoResponse retVal = ((LP2Soft.MedicinaWS.MedicinaWS)(this)).insertarMedicamento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.insertarMedicamentoResponse> LP2Soft.MedicinaWS.MedicinaWS.insertarMedicamentoAsync(LP2Soft.MedicinaWS.insertarMedicamentoRequest request) {
            return base.Channel.insertarMedicamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.MedicinaWS.insertarMedicamentoResponse> insertarMedicamentoAsync(LP2Soft.MedicinaWS.medicamento medicamento) {
            LP2Soft.MedicinaWS.insertarMedicamentoRequest inValue = new LP2Soft.MedicinaWS.insertarMedicamentoRequest();
            inValue.medicamento = medicamento;
            return ((LP2Soft.MedicinaWS.MedicinaWS)(this)).insertarMedicamentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.MedicinaWS.eliminarInventarioResponse LP2Soft.MedicinaWS.MedicinaWS.eliminarInventario(LP2Soft.MedicinaWS.eliminarInventarioRequest request) {
            return base.Channel.eliminarInventario(request);
        }
        
        public int eliminarInventario(LP2Soft.MedicinaWS.inventario inventario) {
            LP2Soft.MedicinaWS.eliminarInventarioRequest inValue = new LP2Soft.MedicinaWS.eliminarInventarioRequest();
            inValue.inventario = inventario;
            LP2Soft.MedicinaWS.eliminarInventarioResponse retVal = ((LP2Soft.MedicinaWS.MedicinaWS)(this)).eliminarInventario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.eliminarInventarioResponse> LP2Soft.MedicinaWS.MedicinaWS.eliminarInventarioAsync(LP2Soft.MedicinaWS.eliminarInventarioRequest request) {
            return base.Channel.eliminarInventarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.MedicinaWS.eliminarInventarioResponse> eliminarInventarioAsync(LP2Soft.MedicinaWS.inventario inventario) {
            LP2Soft.MedicinaWS.eliminarInventarioRequest inValue = new LP2Soft.MedicinaWS.eliminarInventarioRequest();
            inValue.inventario = inventario;
            return ((LP2Soft.MedicinaWS.MedicinaWS)(this)).eliminarInventarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.MedicinaWS.listarInventarioMantenimientoResponse LP2Soft.MedicinaWS.MedicinaWS.listarInventarioMantenimiento(LP2Soft.MedicinaWS.listarInventarioMantenimientoRequest request) {
            return base.Channel.listarInventarioMantenimiento(request);
        }
        
        public LP2Soft.MedicinaWS.inventario[] listarInventarioMantenimiento() {
            LP2Soft.MedicinaWS.listarInventarioMantenimientoRequest inValue = new LP2Soft.MedicinaWS.listarInventarioMantenimientoRequest();
            LP2Soft.MedicinaWS.listarInventarioMantenimientoResponse retVal = ((LP2Soft.MedicinaWS.MedicinaWS)(this)).listarInventarioMantenimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarInventarioMantenimientoResponse> LP2Soft.MedicinaWS.MedicinaWS.listarInventarioMantenimientoAsync(LP2Soft.MedicinaWS.listarInventarioMantenimientoRequest request) {
            return base.Channel.listarInventarioMantenimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarInventarioMantenimientoResponse> listarInventarioMantenimientoAsync() {
            LP2Soft.MedicinaWS.listarInventarioMantenimientoRequest inValue = new LP2Soft.MedicinaWS.listarInventarioMantenimientoRequest();
            return ((LP2Soft.MedicinaWS.MedicinaWS)(this)).listarInventarioMantenimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.MedicinaWS.insertarInventarioResponse LP2Soft.MedicinaWS.MedicinaWS.insertarInventario(LP2Soft.MedicinaWS.insertarInventarioRequest request) {
            return base.Channel.insertarInventario(request);
        }
        
        public int insertarInventario(LP2Soft.MedicinaWS.inventario inventario) {
            LP2Soft.MedicinaWS.insertarInventarioRequest inValue = new LP2Soft.MedicinaWS.insertarInventarioRequest();
            inValue.inventario = inventario;
            LP2Soft.MedicinaWS.insertarInventarioResponse retVal = ((LP2Soft.MedicinaWS.MedicinaWS)(this)).insertarInventario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.insertarInventarioResponse> LP2Soft.MedicinaWS.MedicinaWS.insertarInventarioAsync(LP2Soft.MedicinaWS.insertarInventarioRequest request) {
            return base.Channel.insertarInventarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.MedicinaWS.insertarInventarioResponse> insertarInventarioAsync(LP2Soft.MedicinaWS.inventario inventario) {
            LP2Soft.MedicinaWS.insertarInventarioRequest inValue = new LP2Soft.MedicinaWS.insertarInventarioRequest();
            inValue.inventario = inventario;
            return ((LP2Soft.MedicinaWS.MedicinaWS)(this)).insertarInventarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.MedicinaWS.listarMedicamentosTodosResponse LP2Soft.MedicinaWS.MedicinaWS.listarMedicamentosTodos(LP2Soft.MedicinaWS.listarMedicamentosTodosRequest request) {
            return base.Channel.listarMedicamentosTodos(request);
        }
        
        public LP2Soft.MedicinaWS.medicamento[] listarMedicamentosTodos() {
            LP2Soft.MedicinaWS.listarMedicamentosTodosRequest inValue = new LP2Soft.MedicinaWS.listarMedicamentosTodosRequest();
            LP2Soft.MedicinaWS.listarMedicamentosTodosResponse retVal = ((LP2Soft.MedicinaWS.MedicinaWS)(this)).listarMedicamentosTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarMedicamentosTodosResponse> LP2Soft.MedicinaWS.MedicinaWS.listarMedicamentosTodosAsync(LP2Soft.MedicinaWS.listarMedicamentosTodosRequest request) {
            return base.Channel.listarMedicamentosTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.MedicinaWS.listarMedicamentosTodosResponse> listarMedicamentosTodosAsync() {
            LP2Soft.MedicinaWS.listarMedicamentosTodosRequest inValue = new LP2Soft.MedicinaWS.listarMedicamentosTodosRequest();
            return ((LP2Soft.MedicinaWS.MedicinaWS)(this)).listarMedicamentosTodosAsync(inValue);
        }
    }
}
